# https://spec.openapis.org/oas/v3.1.0#openapi-object
openapi: 3.1.0
info:
  title: Wolf Personal Website API
  description: This is the API for my personal websites
  version: 0.0.1
paths:
  /about:
    get:
      summary: Get about information
      responses:
        200:
          description: About information
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: Wolf
                  age:
                    type: integer
                    example: 18

