GET https://api.nike.com/sport/v3/me/activities/after_time/0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjMwZTQ0MjE1LThjZTAtNDdiZi04Y2Y1LWQwNGViOGM4ZTI1N3NpZyJ9.eyJpYXQiOjE2OTAzMTgxNjMsImV4cCI6MTY5MDMyMTc2MywiaXNzIjoib2F1dGgyYWNjIiwianRpIjoiZmY3MmNlYmYtY2MwZS00MWZkLTkwOTMtZmM3NmQ1Y2UzYzg2IiwiYXVkIjoiY29tLm5pa2UuZGlnaXRhbCIsInNidCI6Im5pa2U6YXBwIiwidHJ1c3QiOjEwMCwibGF0IjoxNjkwMzE4MTYyLCJzY3AiOlsibmlrZS5kaWdpdGFsIl0sInN1YiI6ImNvbS5uaWtlLmNvbW1lcmNlLm5pa2Vkb3Rjb20ud2ViIiwicHJuIjoiYjNlNjdiNjMtOTYxOS00Y2Y3LTg0MGMtM2Y2NmRkNzczNzNmIiwicHJ0IjoibmlrZTpwbHVzIiwibHJzY3AiOiJvcGVuaWQgbmlrZS5kaWdpdGFsIHByb2ZpbGUgZW1haWwgcGhvbmUgZmxvdyBjb3VudHJ5In0.JL-jMm10eD6An6uk_jhHaW_U8h-8VoVWLawEDm4pdDD-RKTpRJUy2M1mQy8ZAdat0YExJjpTU1FdVTE7bMIlciYoOgcxu05dHb5xQZNTHvWqznDftRnJVRt5IKBscHGkL3e1GmqaMFyn9tuEgjlGauocikiibzfoa9x30imNxvqFwhEdFoq2zDO3ZuF68C8FOQpUFdKqKYCK71W8K5kKwlVPBuVwjn7WQCSEZX5LxpaNDdMPRf2RK5zi3t7CSNmt_LS3bEocegN5O-kNX3TFE68CI7ke4VdNuWLMcXG697n0mQv873OoMfw2tNOP1UKX3CxwdX2HSq82CVv-UweGZw