POST http://localhost:3000/api/posts/imageBlocks/
Content-Type: application/json

{
    "title": "Image Blocks",
    "description": "",
    "covers": [],
    "type": "blog",
    "date": "2023",
    "tags": ["hidden"],
    "notes": ""
}
